// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1f0exkCK2NhrhX-qPN4xxtovv1QTt-s',
    appId: '1:121362647591:android:d8d9cdc8d6b0a6d8c4dc02',
    messagingSenderId: '121362647591',
    projectId: 'latihan-firebase-10dbc',
    storageBucket: 'latihan-firebase-10dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8pgwcRZ4UdVqDe5wtltsd-gPqpC6eP4',
    appId: '1:121362647591:ios:b2736f00a41bb3ffc4dc02',
    messagingSenderId: '121362647591',
    projectId: 'latihan-firebase-10dbc',
    storageBucket: 'latihan-firebase-10dbc.appspot.com',
    androidClientId: '121362647591-kd936sqhm83prruk75rn00em949g1qjf.apps.googleusercontent.com',
    iosClientId: '121362647591-6290jqm1vc8r3rkea6o8chqkb3ji6jb5.apps.googleusercontent.com',
    iosBundleId: 'com.fluttergreenrecycle.app',
  );
}
